[package]
name = "bitcoin-rust-lib"
description = "A bare minimal Bitcoin implementation."
version = "0.1.0"
authors = ["Jerry Yuan<yhyuan@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/yhyuan/bitcoin-rust-lib"

[dependencies]
