name: Rust CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            token: ${{ secrets.YOUR_CUSTOM_GITHUB_TOKEN }}

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          stable: true

      - name: Run tests
        run: cargo test
