name: Rust CI

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        # Or @nightly if you want
        uses: dtolnay/rust-toolchain@stable
        # Arguments to pass in

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release

      - name: Run tests
        run: cargo test
